(function() {

  angular.module("mapapp").config(function($translateProvider) {
    $translateProvider.translations("en", {
      footer: {
        getApp: "Get the Mapillary App",
        on: "on",
        directAndroid: "Direct Android .apk link",
        manifesto: "Manifesto",
        about: "About",
        blog: "Blog",
        howItWorks: "How It Works",
        capture: "Capture Instructions",
        using: "Using the App",
        positions: "Open Positions",
        legal: "Legal",
        terms: "Terms and Conditions",
        privacy: "Privacy Policy",
        cookies: "Cookies",
        more: "More",
        business: "Business",
        developers: "Developers",
        integrations: "Integrations",
        embed: "Embed",
        latestUploads: "Latest Uploads",
        report: "Report Issues",
        follow: "Follow"
      },
      landing: {
        more: "More",
        photos: "photos",
        meters: "meters"
      },
      landingBusiness: {
        title: "Mapillary for Business",
        use: "Use Mapillary photos",
        service: "Sign up for a commercial API plan in order to use Mapillary photos and data in your service.",
        create: "Create projects, control access.",
        "private": "Business users can create private projects and control access for a fully private version of Mapillary.",
        integrate: "Integrate photo views",
        gis: "Use our APIs or widget to integrate a complete Mapillary viewer in your application or in your GIS system.",
        learn: "Learn more about our business plans."
      },
      landingHow: {
        one: "1. Get the Mapillary app",
        oneAvailble: "Available for",
        one_from: "and from",
        two: "2. Go out and capture sequences",
        three: "3. Browse, explore, and share places"
      },
      landingWhatyoucan: {
        title: "What you can do with Mapillary",
        section1Map: "Map a place, a town, or someplace new",
        section1Missing: "If your town is missing street view photos, you can add it yourself!",
        section1Examples: "See some great examples at",
        section1And: "and",
        section2Add: "Add roads not on the map, like",
        section2RoadMalaysia: "this road in Malaysia.",
        section2Future: "Record a place for the future to show what it looked like at a point in time, like this",
        section2Coastal: "coastal town.",
        section2NoCars: "Map an area that cannot be reached with street view cars, like the lovely",
        section2Venice: "Venice Beach canals,",
        section2Unmapped: "or the unmapped",
        section2Fishing: "Venice Fishing Pier.",
        section2Share: "Share and show",
        section2Anyone: "Share a place on Mapillary to anyone. Send them a link and it will look good on both mobile and web.",
        section2Embed: "You can embed a Mapillary viewer on any website with",
        section2Widget: "our widget.",
        section2Path: "With this you can show a specific path or route or leave it open for viewers to explore.",
        section2See: "See what you can do on our",
        section2Example: "example page.",
        section3Track: "Track a place over time",
        section3Filter: "Using the filter functions on Mapillary, you can track a place over time.",
        section3Older: "Compare recent pictures to older. Show only summer, only winter, and much more.",
        section3Places: "If you have places and photos that you do don't want to share publicly, you can have private projects. Take a look at our",
        section3Business: "business plans."
      },
      landingSearch: {
        header: "Crowdsourced Street Level Photos",
        search: "Search",
        or: "or",
        anywhere: "Search for places and roads anywhere...",
        contribute: "contribute your own"
      },
      navbar: {
        howItWorks: "How It Works",
        explore: "Explore",
        business: "Business",
        developers: "Developers",
        projects: "Projects",
        me: "Me",
        myProfile: "My Profile",
        manualUploads: "Manual Uploads",
        settings: "Settings",
        signOut: "Sign Out",
        or: "or",
        logIn: "Log In",
        signUp: "Sign Up"
      },
      explore: {
        title: "Explore",
        top5: "Top 5 mappers",
        lastWeek: "Last week",
        thisWeek: "This week",
        user: "user",
        noOfImg: "Number of images",
        toplistsTitle: "Toplists by Region/Country",
        toplistsParagraph: "Browse and explore top contributors by region and/or country.",
        latestUploads: "Latest Uploads"
      },
      profile: {
        uploads: "Uploads",
        connections: "Connections",
        editProfile: "Edit profile",
        uploadedImages: "uploaded images",
        metersMapped: "meters mapped",
        stillProcessing: "still processing",
        recentActivity: "Recent Activity"
      },
      manualUpload: {
        title: "Manually Upload Images",
        paragraph: "Upload images that belong together in one upload, as they will make up a",
        path: "path",
        chooseFiles: "Choose Files",
        tagsRequired: "The following EXIF tags are required:",
        thisImage: "This image",
        goodExample: "is a good example with the required EXIF data, created by",
        seeAlso: "See also the post on",
        usingActionCamera: "using an action camera with Mapillary",
        sampleWorkflow: "for a sample workflow.",
        terms: "By uploading files you agree to the Mapillary",
        termsLink: "terms of service.",
        of: "of",
        imgUploaded: "images uploaded",
        addMoreImages: "Add more images",
        clearAllImages: "Clear all images",
        imageNotUploaded: "Image not uploaded",
        imageUploaded: "Image uploaded",
        clickToSeeInfo: "Click on image on map to see information about the image",
        selectedFile: "Selected file",
        latitude: "Latitude:",
        longitude: "Longitude:",
        angle: "Angle",
        uploaded: "Uploaded",
        remove: "Remove",
        filesWithError: "Files with errors (These files will not be uploaded)",
        filename: "Filename",
        step1: "1. Upload the images to the server. Make sure all your files are green and uploaded.",
        step2: "2. Push your created sequence to Mapillary.",
        selectProject: "Select project (if leave blank in none)",
        pushToMapillary: "Push To Mapillary",
        thankYou: "Thank You!",
        filesUploaded: "Your files have been uploaded to Mapillary",
        check: "Check",
        myUploads: "My Uploads",
        addedSoon: "they will soon be added to the map",
        uploadMore: "Upload More"
      },
      i18nSettings: {
        settings: "Settings",
        profile: "Profile",
        notifications: "Notifications",
        organizations: "Organizations",
        projects: "Projects",
        applications: "Applications",
        newApplication: "New application",
        profilePicture: "Profile picture",
        username: "Username",
        about: "About",
        changePassword: "Change Password",
        members: "Members",
        "delete": "Delete",
        addNewUser: "Add new user",
        add: "Add",
        projects: "Projects",
        create: "Create",
        managedBy: "Managed by",
        members: "Members",
        developerApplications: "Developer Applications",
        registerNewApplication: "Register new application",
        applicationCanAccess: "Application can access",
        users: "Users",
        authorizedApplications: "Authorized Applications",
        access: "Access",
        revoke: "Revoke",
        revokeAll: "Revoke All",
        applicationName: "Application Name",
        company: "Company",
        companyUrl: "Company URL",
        callbackUrl: "Callback URL",
        description: "Description",
        updateApplication: "Update Application",
        deleteApplication: "Delete Application",
        createApplication: "Create Application"
      },
      i18nFilters: {
        filter: "Filter",
        byDate: "Filter by date",
        unit: "Unit",
        week: "Week",
        month: "Month",
        bySeason: "Filter by season",
        otherFilters: "Other filters",
        comments: "Comments",
        panoramas: "Panoramas",
        objects: "Objects",
        from: "from",
        to: "to",
        winter: "Winter",
        spring: "Spring",
        summer: "Summer",
        autumn: "Autumn",
        trafficSigns: "Filter Traffic Signs"
      },
      i18nIm: {
        aboutToFlag: "You are about to flag this image for manual inspection by Mapillary.",
        processingNotice: "This image hasn’t finished processing yet! It will look better soon, promise.",
        share: "Share",
        whatProblem: "What is the problem?",
        imageRotated: "The image is rotated",
        imageNotBlurred: "The image is not blurred correctly",
        imageShouldHide: "The image should be hidden",
        sequenceShouldSplit: "The sequence should be split here",
        ifMapillaryUser: "If you're a Mapillary user, you can manually hide the image from within the 'Edit' image options",
        send: "Send",
        panorama: "Panorama",
        flagged: "Flagged",
        exitPanorama: "Exit Panorama",
        lostFound: "This could be your image. Due to some app problems with Andriod App version 24 we are unable to determine the uploader of this image. If this is you, make a comment below or send us an email at hello@mapillary.com."
      }
    });
    $translateProvider.translations("de", {
      footer: {
        getApp: "Hole dir dir Mapillary App",
        on: "auf",
        directAndroid: "Direkter Link zur Android .apk",
        manifesto: "Manifest",
        about: "Impressum",
        blog: "Blog",
        howItWorks: "Wie's funktioniert",
        capture: "Instruktionen zum Fotografieren",
        using: "Benutzung der App",
        positions: "Offene Stellen",
        legal: "Rechtliches",
        terms: "Benutzungsbedingungen",
        privacy: "Datenschutz",
        cookies: "Cookies",
        more: "Mehr",
        business: "Business",
        developers: "Entwickler",
        integrations: "Integrationen",
        embed: "Integrieren",
        latestUploads: "Neue Bilder",
        report: "Probleme anmelden",
        follow: "Mapillary updates"
      },
      landing: {
        more: "Mehr",
        photos: "Fotos",
        meters: "meter"
      },
      landingBusiness: {
        title: "Mapillary für den kommerziellen Einsatz",
        use: "Mapillary-Bilder anwenden",
        service: "Melden Sie sich für den API plan an, um Mapillary-Bilder und Daten in Ihren Diensten zu verwenden.",
        create: "Projekte erstellen, den Zugang kontrollieren.",
        "private": "Kommerzielle Anwender können private Projekte anlegen und den Zugang zu diesen voll kontrollieren - ein privates Mapillary.",
        integrate: "Photos und Navigation integrieren",
        gis: "Wenden sie unsere Schnittstellen oder die Widgets an, um einen kompletten Mapillary-viewer in Ihrer Applikation, auf ihrer Webseiteoder in Ihrem GIS system zu nutzen.",
        learn: "Mehr Infos über den professionellen Einsatz"
      },
      landingHow: {
        one: "1. Get the Mapillary app",
        oneAvailble: "Available for",
        oneFrom: "and from",
        two: "2. Go out and capture sequences",
        three: "3. Browse, explore, and share places"
      },
      landingWhatyoucan: {
        title: "What you can do with Mapillary",
        section1Map: "Map a place, a town, or someplace new",
        section1Missing: "If your town is missing street view photos, you can add it yourself!",
        section1Examples: "See some great examples at",
        section1And: "and",
        section2Add: "Add roads not on the map, like",
        section2RoadMalaysia: "this road in Malaysia.",
        section2Future: "Record a place for the future to show what it looked like at a point in time, like this",
        section2Coastal: "coastal town.",
        section2NoCars: "Map an area that cannot be reached with street view cars, like the lovely",
        section2Venice: "Venice Beach canals,",
        section2Unmapped: "or the unmapped",
        section2Fishing: "Venice Fishing Pier.",
        section2Share: "Share and show",
        section2Anyone: "Share a place on Mapillary to anyone. Send them a link and it will look good on both mobile and web.",
        section2Embed: "You can embed a Mapillary viewer on any website with",
        section2Widget: "our widget.",
        section2Path: "With this you can show a specific path or route or leave if open for viewers to explore.",
        section2See: "See what you can do on",
        section2Example: "example page.",
        section3Track: "Track a place over time",
        section3Filter: "Using the filter functions on Mapillary, you can track a place over time.",
        section3Older: "Compare recent pictures to older. Show only summer, only winter, and much more.",
        section3Places: "If you have places and photos that you do don't want to share publicly, you can have private projects. Take a look at our",
        section3Business: "business plans."
      },
      landingSearch: {
        header: "Bilder für alle.",
        search: "Suche",
        or: "oder",
        anywhere: "Suche nach Plätzen und Wegen weltweit ...",
        contribute: "mach mit"
      },
      navbar: {
        button_lang_en: "Englisch",
        button_lang_de: "Deutsch",
        howItWorks: "Wie es funktioniert",
        explore: "Entdecken",
        business: "Professionell",
        developers: "Entwickler",
        projects: "Projekte",
        me: "Ich",
        myProfile: "Mein Profil",
        manualUploads: "Manuelle Uploads",
        settings: "Einstellungen",
        signOut: "Ausloggen",
        or: "oder",
        logIn: "Einloggen",
        signUp: "Registrieren"
      },
      explore: {
        title: "Explore",
        top5: "Top 5 mappers",
        lastWeek: "Last week",
        thisWeek: "This week",
        user: "user",
        noOfImg: "Number of images",
        toplistsTitle: "Toplists by Region/Country",
        toplistsParagraph: "Browse and explore top contributors by region and/or country.",
        latestUploads: "Latest Uploads"
      },
      profile: {
        uploads: "Uploads",
        connections: "Connections",
        editProfile: "Edit profile",
        uploadedImages: "uploaded images",
        metersMapped: "meters mapped",
        stillProcessing: "still processing",
        recentActivity: "Recent Activity"
      },
      manualUpload: {
        title: "Manually Upload Images",
        paragraph: "Upload images that belong together in one upload, as they will make up a",
        path: "path",
        chooseFiles: "Choose Files",
        tagsRequired: "The following EXIF tags are required:",
        thisImage: "This image",
        goodExample: "is a good example of a the required EXIF data, created by",
        seeAlso: "See also the post on",
        usingActionCamera: "using an action camera with Mapillary",
        sampleWorkflow: "for a sample workflow.",
        terms: "By uploading files you agree to the Mapillary",
        termsLink: "terms of service.",
        of: "of",
        imgUploaded: "images uploaded",
        addMoreImages: "Add more images",
        clearAllImages: "Clear all images",
        imageNotUploaded: "Image not uploaded",
        imageUploaded: "Image uploaded",
        clickToSeeInfo: "Click on image on map to see information about image",
        selectedFile: "Selected file",
        latitude: "Latitude:",
        longitude: "Longitude:",
        angle: "Angle",
        uploaded: "Uploaded",
        remove: "Remove",
        filesWithError: "Files with errors (These files will not be uploaded)",
        filename: "Filename",
        step1: "1. Upload the images to the server. Make sure all your files are green and uploaded.",
        step2: "2. Push your created sequence to Mapillary.",
        selectProject: "Select project (if leave blank in none)",
        pushToMapillary: "Push To Mapillary",
        thankYou: "Thank You!",
        filesUploaded: "Your files have been uploaded to Mapillary",
        check: "Check",
        myUploads: "My Uploads",
        addedSoon: "they will soon be added to the map",
        uploadMore: "Upload More"
      },
      i18nSettings: {
        settings: "Settings",
        profile: "Profile",
        notifications: "Notifications",
        organizations: "Organizations",
        projects: "Projects",
        applications: "Applications",
        newApplication: "New application",
        profilePicture: "Profile picture",
        username: "Username",
        about: "About",
        changePassword: "Change Password",
        members: "Members",
        "delete": "Delete",
        addNewUser: "Add new user",
        add: "Add",
        projects: "Projects",
        create: "Create",
        managedBy: "Managed by",
        members: "Members",
        developerApplications: "Developer Applications",
        registerNewApplication: "Register new application",
        applicationCanAccess: "Application can access",
        users: "Users",
        authorizedApplications: "Authorized Applications",
        access: "Access",
        revoke: "Revoke",
        revokeAll: "Revoke All",
        applicationName: "Application Name",
        company: "Company",
        companyUrl: "Company URL",
        callbackUrl: "Callback URL",
        description: "Description",
        updateApplication: "Update Application",
        deleteApplication: "Delete Application",
        createApplication: "Create Application"
      },
      i18nFilters: {
        filter: "Filter",
        byDate: "Filter by date",
        unit: "Unit",
        week: "Week",
        month: "Month",
        bySeason: "Filter by season",
        otherFilters: "Other filters",
        comments: "Comments",
        panoramas: "Panoramas",
        objects: "Objects",
        from: "from",
        to: "to",
        winter: "Winter",
        spring: "Spring",
        summer: "Summer",
        autumn: "Autumn",
        trafficSigns: "Filter Traffic Signs"
      },
      i18nIm: {
        aboutToFlag: "You are about to flag this image for manual inspection by Mapillary.",
        processingNotice: "This image hasn’t finished processing yet! It will look better soon, promise.",
        share: "Share",
        whatProblem: "What is the problem?",
        imageRotated: "The image is rotated",
        imageNotBlurred: "The image is not blurred correctly",
        imageShouldHide: "The image should be hidden",
        sequenceShouldSplit: "The sequence should be split here",
        ifMapillaryUser: "If you're a Mapillary user, you can manually hide the image from within the 'Edit' image options",
        send: "Send",
        panorama: "Panorama",
        flagged: "Flagged",
        exitPanorama: "Exit Panorama",
        lostFound: "This could be your image. Due to some app problems with Andriod App version 24 we are unable to determine the uploader of this image. If this is you. Make a comment below or send us an email at hello@mapillary.com."
      }
    });
    $translateProvider.translations("pl", {
      footer: {
        getApp: "Ściągnij aplikację Mapillary",
        on: "on",
        directAndroid: "Bezpośredni link to pliku .apk",
        manifesto: "Manifest",
        about: "O nas",
        blog: "Blog",
        howItWorks: "Jak to działa?",
        capture: "Jak robić zdjęcia",
        using: "Użytkowanie aplikacji",
        positions: "Praca w Mapillary",
        legal: "Ustanowienia Prawne",
        terms: "Zasady korzystania z serwisu",
        privacy: "Polityka prywatoności",
        cookies: "Ciasteczka",
        more: "Więcej",
        business: "Rozwiązania dla biznesu",
        developers: "Dla deweloperów",
        integrations: "Integracja",
        embed: "Widget",
        latestUploads: "Ostatnio dodane",
        report: "Zgłoś błędy",
        follow: "Zaprzyjaźnij się"
      },
      landing: {
        more: "Więcej",
        photos: "zdjęć",
        meters: "metrów"
      },
      landingBusiness: {
        title: "Mapillary dla biznesu",
        use: "Korzystanie ze zdjęć Mapillary",
        service: "Korzystaj z komercyjnego API, by używać zasobów Mapillary we własnych rozwiązaniach.",
        create: "Twórz projekty, zarządzaj dostępem do nich",
        "private": "Klienci biznesowi mogą tworzy projekty i zarzącć tym, kto ma dostęp do prywatnej wersji Mapillary.",
        integrate: "Integruj przeglądanie zasobów",
        gis: "Używaj naszych API lub widgetu by zintegrować przeglądarkę Mapillary wewnątrz własnej aplikacji lub systemu GIS.",
        learn: "Dowiedz się więcej odnośnie rozwiązań biznesowych"
      },
      landingHow: {
        one: "1. Ściągnij aplikację Mapillary",
        oneAvailble: "Dostępna dla",
        oneFrom: "oraz z",
        two: "2. Wyjdź na zewnątrz i dokumentuj świat wokół siebie.",
        three: "3. Przeglądaj, odrkywaj i dziel się miejscami"
      },
      landingWhatyoucan: {
        title: "Co możesz zrobić z Mapillary",
        section1Map: "Mapuj miejsca znane jak i nieznane",
        section1Missing: "Jeśli w twoim mieście brakuje widoku ulicznego, możesz to zmienić, dodaj własne zdjęcia!",
        section1Examples: "Zobacz świetne przykłady z",
        section1And: "oraz",
        section2Add: "Dodawaj dokumentacje miejsc, ktoórych nie ma jeszcze na mapie, jak",
        section2RoadMalaysia: "ta droga w Malezji.",
        section2Future: "Udokumentuj stan miejsca na przyszlłość by pokoazać jak ono wyglądalł w danym momencie w czasie, jak ta",
        section2Coastal: "nabrzeżna wioska",
        section2NoCars: "Mapuj obszary niedostępne dla samochodów, jak te przepiękne",
        section2Venice: "kanalły w Venice Beach,",
        section2Unmapped: "lub niezmapowane",
        section2Fishing: "Weneckie rybackie molo.",
        section2Share: "Dziel się i pokazuj",
        section2Anyone: "Dziel się miejscami z Mapillary z każdym. Wystarczy, że wyślesz linka. Będzie on wyglądać dobrze na urządzeniach mobilnych jak i komputerze.",
        section2Embed: "Możesz osadzić przeglądarkę Mapillary na dolnej stronie korzystając z",
        section2Widget: "naszego widgetu.",
        section2Path: "Dzieęki temu możesz pokazać konkretną scieżkę lub drogę lub udosteępnić możliwość eksploracji dla przeglądających.",
        section2See: "Zobacz co możnesz zrobicć na naszej",
        section2Example: "stronie z przykładami.",
        section3Track: "Śledź rozwój miejsca na podstawie czasu",
        section3Filter: "Używając funkcji filtrowania na Mapillary, możesz śledzić zmiany miejsca na podstawie czasu.",
        section3Older: "Porównuj zdjęcia nowsze z tymi starszymi. Przeglądaj tylko te zrobione podczas, lata, zimy, itd.",
        section3Places: "Jeśli chcesz śledzić miejsca lub masz zdjęcia, którymi nie chcesz się dzielić publicznie, możesz korzystać z prywatnych projektów. Sprawdź nasze",
        section3Business: "plany biznesowe."
      },
      landingSearch: {
        header: "Zdjęcia świata gromadzone przez wszystkich",
        search: "Szukaj",
        or: "lub",
        anywhere: "Odkrywaj miejsca na całym świecie",
        contribute: "dodaj swoje własne…"
      },
      navbar: {
        howItWorks: "Jak to działa?",
        explore: "Odkryj",
        business: "Biznes",
        developers: "Deweloperzy",
        projects: "Projekty",
        me: "Ja",
        myProfile: "Mój profile",
        manualUploads: "Ręczny upload",
        settings: "Ustawienia",
        signOut: "Wyloguj się",
        or: "or",
        logIn: "Logowanie",
        signUp: "Rejestracja"
      },
      explore: {
        title: "Odkryj",
        top5: "Najlepsza 5 maperów",
        lastWeek: "Zeszły tydzień",
        thisWeek: "Ten tydzień",
        user: "użytkownik",
        noOfImg: "Ilość zdjęć",
        toplistsTitle: "Regionalne/Krajowe toplisty",
        toplistsParagraph: "Przeglądaj top listy użytkowników na podstawie regionu i/lub kraju.",
        latestUploads: "Ostation dodane"
      },
      profile: {
        uploads: "Dodane sekwencje",
        connections: "Połączenia",
        editProfile: "Edycja profile",
        uploadedImages: "dodanych zdjęć",
        metersMapped: "zmapowanych metrów",
        stillProcessing: "wciąż przetwarzanych",
        recentActivity: "Ostania aktywność"
      },
      manualUpload: {
        title: "Ręczny upload zdjęć",
        paragraph: "Dodaj zdjęcia należące do jednego uploadu, tak by tworzyły",
        path: "ścieżkę",
        chooseFiles: "Wybierz pliki",
        tagsRequired: "Nasteępujące tagi EXIF są wymagane:",
        thisImage: "To zdjęcie",
        goodExample: "jest dobrym przykładem wymaganych tagoów EXIF; zrobione przez ",
        seeAlso: "Sprawdź również post n.t.",
        usingActionCamera: "użytkowania kamer GoPro i Virb z Mapillary",
        sampleWorkflow: "by zobaczyć przkładowy proces.",
        terms: "Poprzez upload plików zgadzasz się na",
        termsLink: "warunki korzystania z Mapillary.",
        of: "z",
        imgUploaded: "zdjęc dodanych",
        addMoreImages: "Dodaj więcej zdjęć",
        clearAllImages: "Wyczyść wszystkie zdjęcia",
        imageNotUploaded: "Zdjęcia nie dodane",
        imageUploaded: "Zdjęcie dodane",
        clickToSeeInfo: "Kliknij na mapę by zobaczyć więcej informacji n.t. zdjęcia",
        selectedFile: "Wybrany plik",
        latitude: "długość geo.:",
        longitude: "szerokość geo.:",
        angle: "kąt",
        uploaded: "Dodane",
        remove: "Usunięte",
        filesWithError: "Zdjęcia nie dodane (Nie zostaną wrzucone na serwer)",
        filename: "Nazwa pliku",
        step1: "1. Dodaj zdjęcia na serwer. Sprawdź czy wszystkie pliki są oznaczone na zielono i wrzucone.",
        step2: "2. Załaduje twoje zdjęcia na Mapillary.",
        selectProject: "Wybierz projekt (jeśli zostawisz puste, nie znajdą się one w projekcie)",
        pushToMapillary: "Załaduj na Mapillary",
        thankYou: "Dzięki!",
        filesUploaded: "Twoje zdjęcia zostały załadowane na Mapillary",
        check: "Sprawdź",
        myUploads: "Moje uploady",
        addedSoon: "znajdą się niedługo na mapie",
        uploadMore: "Załaduj więcej"
      },
      i18nSettings: {
        settings: "Ustawienia",
        profile: "Profil",
        notifications: "Powiadomienia",
        organizations: "Organizacje",
        projects: "Projekty",
        applications: "Applikacje",
        newApplication: "Nowa aplikacja",
        profilePicture: "Zdjęcie profilowe",
        username: "Nazwa użytkownika",
        about: "O mnie",
        changePassword: "Zmień hasło",
        members: "Członkowie",
        "delete": "usuń",
        addNewUser: "Dodaj użytkownika",
        add: "Dodaj",
        projects: "Projekty",
        create: "Utwórz",
        managedBy: "Zarządzany przez",
        developerApplications: "Aplikacje deweloperskie",
        registerNewApplication: "Zarejestruj nową aplikację",
        applicationCanAccess: "Aplikacja ma dostęp do",
        users: "Użytkownicy",
        authorizedApplications: "Autoryzowane aplikacje",
        access: "Dostęp",
        revoke: "Odmów dostępu",
        revokeAll: "Odmów dostępu wszystkim",
        applicationName: "Nazwa aplikacji",
        company: "Firma",
        companyUrl: "URL firmy",
        callbackUrl: "URL zwrotny",
        description: "Opis",
        updateApplication: "Update'uj aplikację",
        deleteApplication: "Usuń aplikację",
        createApplication: "Utwórz aplikację"
      },
      i18nFilters: {
        filter: "Filtruj",
        byDate: "Filtruj po dacie",
        unit: "Jednostka",
        week: "Tydzień",
        month: "Miesiąc",
        bySeason: "Filtruj po sezonie",
        otherFilters: "Inne filtry",
        comments: "Komentarze",
        panoramas: "Panoramy",
        objects: "Objekty",
        from: "od",
        to: "do",
        winter: "Zima",
        spring: "Wiosna",
        summer: "Lato",
        autumn: "Jesień",
        trafficSigns: "Filtruj znaki drogowe"
      },
      i18nIm: {
        aboutToFlag: "Za chwilę oflagujesz zdjęcie do ręcznej inspekcji przez Mapillary.",
        processingNotice: "Zdjęcie jeszcz nie zostalło przetworzone. Niedługo beędzie wyglądać lepiej, obiecujemy.",
        share: "Dziel się",
        whatProblem: "Co jest nie tak?",
        imageRotated: "Zdjęcie jest odwrócone",
        imageNotBlurred: "Zdjęcie nie jest poprawnie zazmazane.",
        imageShouldHide: "To zdjeęcie powinno być ukryte",
        sequenceShouldSplit: "Sekwencja powinna być przerwana w tym miejscu",
        ifMapillaryUser: "Jeśli jesteś uzżytkownikiem Mapillary, możesz reęcznie ukryć zdjęcie, klikając na 'Edytuj'.",
        send: "Wyślij",
        panorama: "Panorama",
        flagged: "Oflagowane",
        exitPanorama: "Wyjdź z panoramy",
        lostFound: "To może być twoje zdjęcie. W związku z problemem z aplikacją na Androida v. 24, nie jesteśmy w stanie zlokalizowacć kto jest właścicielem tego zdjęcia. Jeśli Ty nim jesteś, zostaw komentarz pod tym zdjęciem, lub podeślij mejla na hello@mapillary.com."
      }
    });
    $translateProvider.translations("zh-CN", {
      footer: {
        getApp: "下载 Mapillary 应用",
        on: "在",
        directAndroid: "安卓 .apk 下载链接",
        manifesto: "理念",
        about: "关于",
        blog: "博客",
        howItWorks: "如何使用",
        capture: "拍摄方法",
        using: "使用App",
        positions: "加入我们",
        legal: "法律条款",
        terms: "服务条款和条件",
        privacy: "私隐条款",
        cookies: "Cookies",
        more: "更多",
        business: "解决方案",
        developers: "开发者",
        integrations: "合作案例",
        embed: "嵌入",
        latestUploads: "最新街景",
        report: "报告",
        follow: "关注我们"
      },
      landing: {
        more: "更多",
        photos: "张街景照片",
        meters: "米"
      },
      landingBusiness: {
        title: "Mapillary 商业解决方案",
        use: "使用 Mapillary 照片",
        service: "注册商用API来使用 Mapillary 的街景照片和衍生数据.",
        create: "创建项目，控制访问权限和分享",
        "private": "商业用户可以创建私人项目来使用 Mapillary 以推动内部信息分享与合作.",
        integrate: "融合街景",
        gis: "使用 Mapillary 的API或者Widget，将街景融合到你的应用程序或者地理信息系统(GIS)中.",
        learn: "了解更多 Mapillary 的商业解决方案"
      },
      landingHow: {
        one: "1. 下载Mapillary应用",
        oneAvailble: "",
        oneFrom: "和",
        two: "2. 拍摄你身边的街景",
        three: "3. 浏览, 发现, 和分享街景"
      },
      landingWhatyoucan: {
        title: "你可以用Mapillary",
        section1Map: "记录一个海滩,小镇或者地图上沒有标记的地方",
        section1Missing: "如果你住的地方没有街景，你可以创建属于自己的街景！",
        section1Examples: "看看这些有趣的例子：",
        section1And: "和",
        section2Add: "标记地图上没有的路，例如",
        section2RoadMalaysia: "这段在马来西亚的公路.",
        section2Future: "记录一个地方的历史,例如这个经历了很多变迁的",
        section2Coastal: "海滨小镇.",
        section2NoCars: "拍摄那些街景车无法进入的地方，例如美丽的",
        section2Venice: "威尼斯海滩运河",
        section2Unmapped: "和",
        section2Fishing: "威尼斯渔人码头.",
        section2Share: "展示和分享",
        section2Anyone: "通过Mapillary, 在网页和移动设备上与任何人分享你到过的地方.",
        section2Embed: "你可以很容易在网站上嵌入Mapillary的街景浏览功能, 通过",
        section2Widget: "我们的Widget.",
        section2Path: "这样你可以给你的家人, 朋友 或者客户在地图上展示例如一段乡间小径或在建公路.",
        section2See: "以下有很多启发人的",
        section2Example: "例子.",
        section3Track: "追溯一个地方的历史",
        section3Filter: "使用Mapillary时间筛选功能, 你可以穿梭时间的纬度来欣赏或者考察一个地方的变迁",
        section3Older: ", 或者感受同一地方四季的风光.",
        section3Places: "如果你希望对你所记录的地方保密，你也可以创建私人项目. 更多细节可以参考",
        section3Business: "我们的解决方案."
      },
      landingSearch: {
        header: "人人街景",
        search: "搜索",
        or: "或者",
        anywhere: "搜索任何街道,小镇或者城市...",
        contribute: "创建你自己的街景"
      },
      navbar: {
        howItWorks: "如何使用",
        explore: "发现",
        business: "商业解决方案",
        developers: "开发者",
        projects: "项目",
        me: "我",
        myProfile: "我的主页",
        manualUploads: "上传照片",
        settings: "设置",
        signOut: "登出",
        or: "或",
        logIn: "登入",
        signUp: "注册"
      },
      explore: {
        title: "发现",
        top5: "前五榜单",
        lastWeek: "上周",
        thisWeek: "本周",
        user: "用户",
        noOfImg: "照片",
        toplistsTitle: "区域/国家 排名",
        toplistsParagraph: "浏览各个区域/国家的用户排名",
        latestUploads: "最新街景"
      },
      profile: {
        uploads: "照片",
        connections: "关联街景",
        editProfile: "设置主页",
        uploadedImages: "已上传",
        metersMapped: "米 已覆盖",
        stillProcessing: "正在处理",
        recentActivity: "最近动态"
      },
      manualUpload: {
        title: "上传街景照片",
        paragraph: "建议将属于同一地方或者路段的照片一起上传 - ",
        path: "例子",
        chooseFiles: "选择文件",
        tagsRequired: "你所上传的照片必须包含以下的EXIF数据:",
        thisImage: "例如这张照片 ",
        goodExample: "包含了上述所须的EXIF数据, 上传者:",
        seeAlso: "你也可以参照这篇博客来了解",
        usingActionCamera: "如何用运动相机来创建 Mapillary 街景",
        sampleWorkflow: "",
        terms: "上传照片意味着你同意 Mapillary ",
        termsLink: "服务条款.",
        of: "",
        imgUploaded: "已上传照片",
        addMoreImages: "上传更多",
        clearAllImages: "清空",
        imageNotUploaded: "未上传照片",
        imageUploaded: "已上传照片",
        clickToSeeInfo: "单击照片查看更多信息",
        selectedFile: "选择文件",
        latitude: "纬度:",
        longitude: "经度:",
        angle: "朝向",
        uploaded: "上传成功",
        remove: "删除",
        filesWithError: "出错的文件 (这些文件将不会被上传)",
        filename: "文件名",
        step1: "1. 准备上传照片到服务器. 请确认地图上的文件标记转为绿色以保证成功上传",
        step2: "2. 推送你的街景照片到 Mapillary",
        selectProject: "选择项目 (或保留空白)",
        pushToMapillary: "推送到 Mapillary",
        thankYou: "谢谢!",
        filesUploaded: "你的照片已被成功上传到 Mapillary",
        check: "确认",
        myUploads: "我的上传",
        addedSoon: "这些照片将会不久后在地图上呈现",
        uploadMore: "上传更多"
      },
      i18nSettings: {
        settings: "设置",
        profile: "主页",
        notifications: "通知",
        organizations: "公司/机构",
        projects: "项目",
        applications: "应用",
        newApplication: "新的应用",
        profilePicture: "个性照片",
        username: "用户名",
        about: "关于",
        changePassword: "更改密码",
        members: "成员",
        "delete": "删除",
        addNewUser: "创建用户",
        add: "增加",
        projects: "项目",
        create: "创建",
        managedBy: "项目管理人:",
        members: "成员",
        developerApplications: "开发者应用",
        registerNewApplication: "注册新的应用",
        applicationCanAccess: "此应用可以访问",
        users: "用户",
        authorizedApplications: "已授权应用",
        access: "可以访问",
        revoke: "撤销",
        revokeAll: "撤销所有",
        applicationName: "应用名称",
        company: "公司",
        companyUrl: "公司链接",
        callbackUrl: "回调链接",
        description: "描述",
        updateApplication: "更新应用",
        deleteApplication: "删除应用",
        createApplication: "创建应用"
      },
      i18nFilters: {
        filter: "筛选",
        byDate: "时间筛选",
        unit: "单位",
        week: "星期",
        month: "月份",
        bySeason: "季节筛选",
        otherFilters: "其他筛选条件",
        comments: "评论",
        panoramas: "全景",
        objects: "物体",
        from: "从",
        to: "到",
        winter: "冬",
        spring: "春",
        summer: "夏",
        autumn: "秋",
        trafficSigns: "交通标志"
      },
      i18nIm: {
        aboutToFlag: "发现有问题的照片? 请帮助我们修正.",
        processingNotice: "我们正在努力处理这张照片. 感谢你的耐心等待!",
        share: "分享",
        whatProblem: "这张照片有什么问题?",
        imageRotated: "这张照片的方向不正确",
        imageNotBlurred: "这张照片中模糊的区域不准确",
        imageShouldHide: "这张照片应该被隐藏",
        sequenceShouldSplit: "这个街景序列应该在这里被切分",
        ifMapillaryUser: "如果你已经是 Mapillary 用户, 你可以使用'编辑'功能来隐藏这张照片。",
        send: "发送",
        panorama: "全景",
        flagged: "报告",
        exitPanorama: "退出全景",
        lostFound: "由于安卓2.4版本应用的问题, 我们无法确认这张照片的上传者. 如果这张照片是属于你的，你可以发送邮件到hello@mapillary.com认领. "
      }
    });
    $translateProvider.translations("zh-TW", {
      footer: {
        getApp: "下載 Mapillary 應用",
        on: "在",
        directAndroid: "安卓 .apk 下載鏈接",
        manifesto: "理念",
        about: "關於",
        blog: "博客",
        howItWorks: "如何使用",
        capture: "拍攝方法",
        using: "使用App",
        positions: "加入我們",
        legal: "法律條款",
        terms: "服務條款和條件",
        privacy: "私隱條款",
        cookies: "Cookies",
        more: "更多",
        business: "解決方案",
        developers: "開發者",
        integrations: "合作案例",
        embed: "嵌入",
        latestUploads: "最新街景",
        report: "報告",
        follow: "關注我們"
      },
      landing: {
        more: "更多",
        photos: "張街景照片",
        meters: "米"
      },
      landingBusiness: {
        title: "Mapillary 商業解決方案",
        use: "使用 Mapillary 照片",
        service: "注冊商用API來使用 Mapillary 的街景照片和衍生數據.",
        create: "創建項目，控制訪問權限和分享",
        "private": "商業用戶可以創建私人項目來使用 Mapillary 以推動內部信息分享與合作.",
        integrate: "融合街景",
        gis: "使用 Mapillary 的API或者Widget，將街景融合到你的應用程序或者地理信息系統(GIS)中.",
        learn: "了解更多 Mapillary 的商業解決方案"
      },
      landingHow: {
        one: "1. 下載Mapillary應用",
        oneAvailble: "",
        oneFrom: "和",
        two: "2. 拍攝你身邊的街景",
        three: "3. 瀏覽, 發現, 和分享街景"
      },
      landingWhatyoucan: {
        title: "你可以用Mapillary",
        section1Map: "記錄一個海灘,小鎮或者地圖上沒有標記的地方",
        section1Missing: "如果你住的地方沒有街景，你可以創建屬於自己的街景！",
        section1Examples: "看看這些有趣的例子：",
        section1And: "和",
        section2Add: "標記地圖上沒有的路，例如",
        section2RoadMalaysia: "這段在馬來西亞的公路.",
        section2Future: "記錄一個地方的歷史,例如這個經歷了很多變遷的",
        section2Coastal: "海濱小鎮.",
        section2NoCars: "拍攝那些街景車無法進入的地方，例如美麗的",
        section2Venice: "威尼斯海灘運河",
        section2Unmapped: "和",
        section2Fishing: "威尼斯漁人碼頭.",
        section2Share: "展示和分享",
        section2Anyone: "通過Mapillary, 在網頁和移動設備上與任何人分享你到過的地方.",
        section2Embed: "你可以很容易在網站上嵌入Mapillary的街景瀏覽功能, 通過",
        section2Widget: "我們的Widget.",
        section2Path: "這樣你可以給你的家人, 朋友 或者客戶在地圖上展示例如一段鄉間小徑或在建公路.",
        section2See: "以下有很多啟發人的",
        section2Example: "例子.",
        section3Track: "追溯一個地方的歷史",
        section3Filter: "使用Mapillary時間篩選功能, 你可以穿梭時間的緯度來欣賞或者考察一個地方的變遷",
        section3Older: ", 或者感受同一地方四季的風光.",
        section3Places: "如果你希望對你所記錄的地方保密，你也可以創建私人項目. 更多細節可以參考",
        section3Business: "我們的解決方案."
      },
      landingSearch: {
        header: "人人街景",
        search: "搜索",
        or: "或者",
        anywhere: "搜索任何街道,小鎮或者城市...",
        contribute: "創建你自己的街景"
      },
      navbar: {
        howItWorks: "如何使用",
        explore: "發現",
        business: "商業解決方案",
        developers: "開發者",
        projects: "項目",
        me: "我",
        myProfile: "我的主頁",
        manualUploads: "上傳照片",
        settings: "設置",
        signOut: "登出",
        or: "或",
        logIn: "登入",
        signUp: "注冊"
      },
      explore: {
        title: "發現",
        top5: "前五榜單",
        lastWeek: "上周",
        thisWeek: "本周",
        user: "用戶",
        noOfImg: "照片",
        toplistsTitle: "區域/國家 排名",
        toplistsParagraph: "瀏覽各個區域/國家的用戶排名",
        latestUploads: "最新街景"
      },
      profile: {
        uploads: "照片",
        connections: "關聯街景",
        editProfile: "設置主頁",
        uploadedImages: "已上傳",
        metersMapped: "米 已覆蓋",
        stillProcessing: "正在處理",
        recentActivity: "最近動態"
      },
      manualUpload: {
        title: "上傳街景照片",
        paragraph: "建議將屬於同一地方或者路段的照片一起上傳 - ",
        path: "例子",
        chooseFiles: "選擇文件",
        tagsRequired: "你所上傳的照片必須包含以下的EXIF數據:",
        thisImage: "例如這張照片 ",
        goodExample: "包含了上述所須的EXIF數據, 上傳者:",
        seeAlso: "你也可以參照這篇博客來了解",
        usingActionCamera: "如何用運動相機來創建 Mapillary 街景",
        sampleWorkflow: "",
        terms: "上傳照片意味著你同意 Mapillary ",
        termsLink: "服務條款.",
        of: "",
        imgUploaded: "已上傳照片",
        addMoreImages: "上傳更多",
        clearAllImages: "清空",
        imageNotUploaded: "未上傳照片",
        imageUploaded: "已上傳照片",
        clickToSeeInfo: "單擊照片查看更多信息",
        selectedFile: "選擇文件",
        latitude: "緯度:",
        longitude: "經度:",
        angle: "朝向",
        uploaded: "上傳成功",
        remove: "刪除",
        filesWithError: "出錯的文件 (這些文件將不會被上傳)",
        filename: "文件名",
        step1: "1. 准備上傳照片到服務器. 請確認地圖上的文件標記轉為綠色以保証成功上傳",
        step2: "2. 推送你的街景照片到 Mapillary",
        selectProject: "選擇項目 (或保留空白)",
        pushToMapillary: "推送到 Mapillary",
        thankYou: "謝謝!",
        filesUploaded: "你的照片已被成功上傳到 Mapillary",
        check: "確認",
        myUploads: "我的上傳",
        addedSoon: "這些照片將會不久后在地圖上呈現",
        uploadMore: "上傳更多"
      },
      i18nSettings: {
        settings: "設置",
        profile: "主頁",
        notifications: "通知",
        organizations: "公司/機構",
        projects: "項目",
        applications: "應用",
        newApplication: "新的應用",
        profilePicture: "個性照片",
        username: "用戶名",
        about: "關於",
        changePassword: "更改密碼",
        members: "成員",
        "delete": "刪除",
        addNewUser: "創建用戶",
        add: "增加",
        projects: "項目",
        create: "創建",
        managedBy: "項目管理人:",
        members: "成員",
        developerApplications: "開發者應用",
        registerNewApplication: "注冊新的應用",
        applicationCanAccess: "此應用可以訪問",
        users: "用戶",
        authorizedApplications: "已授權應用",
        access: "可以訪問",
        revoke: "撤銷",
        revokeAll: "撤銷所有",
        applicationName: "應用名稱",
        company: "公司",
        companyUrl: "公司鏈接",
        callbackUrl: "回調鏈接",
        description: "描述",
        updateApplication: "更新應用",
        deleteApplication: "刪除應用",
        createApplication: "創建應用"
      },
      i18nFilters: {
        filter: "篩選",
        byDate: "時間篩選",
        unit: "單位",
        week: "星期",
        month: "月份",
        bySeason: "季節篩選",
        otherFilters: "其他篩選條件",
        comments: "評論",
        panoramas: "全景",
        objects: "物體",
        from: "從",
        to: "到",
        winter: "冬",
        spring: "春",
        summer: "夏",
        autumn: "秋",
        trafficSigns: "交通標志"
      },
      i18nIm: {
        aboutToFlag: "發現有問題的照片? 請幫助我們修正.",
        processingNotice: "我們正在努力處理這張照片. 感謝你的耐心等待!",
        share: "分享",
        whatProblem: "這張照片有什麼問題?",
        imageRotated: "這張照片的方向不正確",
        imageNotBlurred: "這張照片中模糊的區域不准確",
        imageShouldHide: "這張照片應該被隱藏",
        sequenceShouldSplit: "這個街景序列應該在這裡被切分",
        ifMapillaryUser: "如果你已經是 Mapillary 用戶, 你可以使用'編輯'功能來隱藏這張照片。",
        send: "發送",
        panorama: "全景",
        flagged: "報告",
        exitPanorama: "退出全景",
        lostFound: "由於安卓2.4版本應用的問題, 我們無法確認這張照片的上傳者. 如果這張照片是屬於你的，你可以發送郵件到hello@mapillary.com認領. "
      }
    });
    $translateProvider.translations("sv", {
      footer: {
        getApp: "Ladda ner Mapillary appen",
        on: "på",
        directAndroid: "Direkt Android .apk link",
        manifesto: "Manifesto",
        about: "Om",
        blog: "Blog",
        howItWorks: "Så funkar det",
        capture: "Instruktioner",
        using: "Använda Appen",
        positions: "Lediga tjänster",
        legal: "Juridiskt",
        terms: "Användarvillkor",
        privacy: "Integritetspolicy",
        cookies: "Cookies",
        more: "More",
        business: "Företag",
        developers: "Utvecklare",
        integrations: "Integrationer",
        embed: "Integrera",
        latestUploads: "Senaste Uploads",
        report: "Reportera Problem",
        follow: "Följ"
      },
      landing: {
        more: "Mer",
        photos: "foton",
        meters: "meter"
      },
      landingBusiness: {
        title: "Mapillary för företag",
        use: "Använda Mapillarybilder",
        service: "Signa upp för ett kommersiellt API abonnemang för att använda Mapillarybilder och data i din tjänst.",
        create: "Skapa projekt, kontrollera åtkomst.",
        "private": "Företagsanvändare kan skapa privata projekt och kontrollera åtkomst för en helt skyddad version av Mapillary.",
        integrate: "Integrera bilder",
        gis: "Använd vårt API och vår widget för att integrera en komplett Mapillary viewer i din tjänst eller i ditt GIS system.",
        learn: "Läs mer om våra kommersiella erbjudanden."
      },
      landingHow: {
        one: "1. Ladda ner Mapillary appen",
        oneAvailble: "Tillgänglig för",
        oneFrom: "och från",
        two: "2. Gå ut och ta bildsekvenser",
        three: "3. Surfa, utforska, och dela platser"
      },
      landingWhatyoucan: {
        title: "Vad du kan göra med Mapillary",
        section1Map: "Kartlägga en plats, en stad, eller ett nytt ställe",
        section1Missing: "Om din stad saknar gatubilder kan du lägga till det själv!",
        section1Examples: "Se några fantastiska exempel på",
        section1And: "och",
        section2Add: "Lägg till vägar som inte finns på kartan, som",
        section2RoadMalaysia: "denna väg i Malaysia.",
        section2Future: "Dokumentera en plats för framtiden för att visa hur det såg ut vid en given tidspunkt, som denna",
        section2Coastal: "kuststad.",
        section2NoCars: "Kartlägg ett område som inte kan nås med gatuvybilar, some de vackra",
        section2Venice: "Venice Beach kanalerna,",
        section2Unmapped: "eller den icke-kartlagda",
        section2Fishing: "Venice Fishing Pier.",
        section2Share: "Dela och visa",
        section2Anyone: "Dela en plats på Mapillary till vem som helst. Skicka en länk som ser bra ut på både på mobil och web.",
        section2Embed: "Du kan integrera en Mapillary viewer på vilken hemsida som helst med",
        section2Widget: "vår widget.",
        section2Path: "Med denna kan du visa en given sträcka eller rutt eller lämna navigeringen öppen för besökare att utforska.",
        section2See: "Läs med vad du kan göra på vår",
        section2Example: "exempelsida.",
        section3Track: "Följ en plats över tid",
        section3Filter: "Med filterfunktionerna på Mapillary kan du följa en plats över tid.",
        section3Older: "Jämför nya bilder med gamla. Visa bara sommar, bara vinter, och mycket mer.",
        section3Places: "Om du har platser och bilder som du inte vill dela publikt kan du skapa privata projekt. Ta en titt på våra",
        section3Business: "kommersiella erbjudanden."
      },
      landingSearch: {
        header: "Crowdsourcade Gatubilder",
        search: "Sök",
        or: "eller",
        anywhere: "Sök efter platser och vägar överallt...",
        contribute: "skapa egna"
      },
      navbar: {
        howItWorks: "Så funkar det",
        explore: "Utforska",
        business: "Företag",
        developers: "Utvecklare",
        projects: "Projekt",
        me: "Mig",
        myProfile: "Min Profil",
        manualUploads: "Manuell Uploads",
        settings: "Inställningar",
        signOut: "Logga Ut",
        or: "eller",
        logIn: "Logga In",
        signUp: "Skapa konto"
      },
      explore: {
        title: "Utforska",
        top5: "Top 5 mappers",
        lastWeek: "Förra veckan",
        thisWeek: "Denna veckan",
        user: "användare",
        noOfImg: "Antal bilder",
        toplistsTitle: "Toplistor per Region/Land",
        toplistsParagraph: "Surfa och utforska toppanvändare per region och/eller land.",
        latestUploads: "Senaste Uploads"
      },
      profile: {
        uploads: "Uploads",
        connections: "Kopplingar",
        editProfile: "Redigera profil",
        uploadedImages: "upladdade bilder",
        metersMapped: "meter kartlagda",
        stillProcessing: "fortfarande i behandling",
        recentActivity: "Senaste Aktiviteter"
      },
      manualUpload: {
        title: "Manuelt Upladdade Bilder",
        paragraph: "Ladda upp bilder som hör ihop i en sekvens i en upladdning, de kommer att utgöra en",
        path: "sekvens",
        chooseFiles: "Välj Bilder",
        tagsRequired: "Följande EXIF taggar är nödvändiga:",
        thisImage: "Denna bild",
        goodExample: "är ett bra exempel med nödvändig EXIF data, skapad av",
        seeAlso: "Se också blogginlägget om",
        usingActionCamera: "att använda en actionkamera med Mapillary",
        sampleWorkflow: "för ett enkelt arbetssätt.",
        terms: "Genom att ladda upp bilder godkänner du Mapillarys",
        termsLink: "användarvilkor.",
        of: "av",
        imgUploaded: "uppladdade bilder",
        addMoreImages: "Lägg till mer bilder",
        clearAllImages: "Rensa alla bilder",
        imageNotUploaded: "Bilden laddades inte upp",
        imageUploaded: "Bilden laddades upp",
        clickToSeeInfo: "Klicka på en bild på kartan för att se information om bilden.",
        selectedFile: "Vald bild",
        latitude: "Latitude:",
        longitude: "Longitude:",
        angle: "Riktning",
        uploaded: "Uppladdade",
        remove: "Ta bort",
        filesWithError: "Bilder med fel (Dessa filer kommer inte att laddas upp)",
        filename: "Filnamn",
        step1: "1. Ladda upp bilder till servern. Se till att alla bilder är gröna och uppladdade.",
        step2: "2. Skicka din sekvens till Mapillary.",
        selectProject: "Välj projekt (om tomt inget projekt)",
        pushToMapillary: "Skicka Till Mapillary",
        thankYou: "Tack!",
        filesUploaded: "Dina bilder har laddats upp till Mapillary",
        check: "Kolla på",
        myUploads: "Mina Uploads",
        addedSoon: "de kommer snart läggas ut på kartan",
        uploadMore: "Ladda upp mer"
      },
      i18nSettings: {
        settings: "Inställningar",
        profile: "Profil",
        notifications: "Meddelanden",
        organizations: "Organizationer",
        projects: "Projekt",
        applications: "Appar",
        newApplication: "Ny app",
        profilePicture: "Profilbild",
        username: "Användarnamn",
        about: "Om",
        changePassword: "Byt Lösenord",
        members: "Medlemmar",
        "delete": "Radera",
        addNewUser: "Lägg till användare",
        add: "Lägg till",
        projects: "Projekt",
        create: "Skapa",
        managedBy: "Hanteras av",
        members: "Medlemmar",
        developerApplications: "Utvecklarappar",
        registerNewApplication: "Registrera ny app",
        applicationCanAccess: "App kan komma åt",
        users: "Användare",
        authorizedApplications: "Godkända Appar",
        access: "Åtkomst",
        revoke: "Återkalla",
        revokeAll: "Återkalla Alla",
        applicationName: "App Namn",
        company: "Företag",
        companyUrl: "Företag URL",
        callbackUrl: "Callback URL",
        description: "Beskrivning",
        updateApplication: "Updatera App",
        deleteApplication: "Radera App",
        createApplication: "Skapa App"
      },
      i18nFilters: {
        filter: "Filter",
        byDate: "Filtrera med datum",
        unit: "Enhet",
        week: "Vecka",
        month: "Månad",
        bySeason: "Filtrera med årstid",
        otherFilters: "Andra filter",
        comments: "Kommentarer",
        panoramas: "Panorama",
        objects: "Igenkänning",
        from: "från",
        to: "till",
        winter: "Vinter",
        spring: "Vår",
        summer: "Sommar",
        autumn: "Höst",
        trafficSigns: "Filtrera Trafikskyltar"
      },
      i18nIm: {
        aboutToFlag: "Du kommer rapportera denna bild för manuell kontroll av Mapillary.",
        processingNotice: "Denna bild är inte färdigprocessad ännu. Det kommer se bättre ut snart, vi lovar.",
        share: "Dela",
        whatProblem: "Vad är det som är fel?",
        imageRotated: "Bilden är roterad",
        imageNotBlurred: "Bilden är inte korrekt suddad",
        imageShouldHide: "Bilden bör gömmas",
        sequenceShouldSplit: "Sekvensen bör delas här",
        ifMapillaryUser: "Om du är en Mapillaryanvändare så kan du själv gömma bilden under 'Redigera'",
        send: "Skicka",
        panorama: "Panorama",
        flagged: "Flaggad",
        exitPanorama: "Lämna Panorama",
        lostFound: "Detta skulle kunna vara din bild. Pga problem med Android App version 24 kan vi inte se vem som laddat upp denna bilden. Om det är du, lämna en kommentar eller maila hello@mapillary.com."
      }
    });
    $translateProvider.fallbackLanguage("en");
    $translateProvider.preferredLanguage("en");
    return $translateProvider.useLocalStorage();
  });

}).call(this);
